name: Test
on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda:
    name: conda ${{ matrix.sys.compiler }} (${{ matrix.sys.os }})
    timeout-minutes: 60
    runs-on: ${{ matrix.sys.os }}
    strategy:
      fail-fast: false
      matrix:
        sys:
          - { package: clangxx, compiler: clang++, os: macOS-latest }
    steps:
      - uses: actions/checkout@v5
      - name: Setup ccache . . .
        uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
          install_ccache: true
      - name: "Create micromamba environment"
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: builder
          create-args: >-
            libcxx
            make
            automake
            autoconf
            libtool
            pkg-config
            compiler-rt
            ${{ matrix.sys.package }}
      - name: "Set environment variables . . ."
        run: |
          echo "PKG_CONFIG_PATH=$MAMBA_ROOT_PREFIX/envs/builder/lib/pkgconfig:$MAMBA_ROOT_PREFIX/envs/builder/share/pkgconfig:/usr/local/lib/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$MAMBA_ROOT_PREFIX/envs/builder/lib:/usr/local/lib" >> $GITHUB_ENV
          echo "PATH=$MAMBA_ROOT_PREFIX/envs/builder/bin:$PATH" >> $GITHUB_ENV
      - name: Compiler info . . .
        run: ${{ matrix.sys.compiler }} --version
      - name: Configure . . .
        run: |
          ./autogen.sh
          ./configure CXX="ccache ${{ matrix.sys.compiler }} -v"
      - name: Build libsemigroups . . .
        run: make -j4
      - name: Build test_all . . .
        run: make test_all -j4
      - name: Run the quick and standard tests . . .
        run: ./test_all "[quick],[standard]"
